// <auto-generated />
using System;
using Korp.Faturamento.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Korp.Faturamento.Infrastructure.Migrations
{
    [DbContext(typeof(FaturamentoDbContext))]
    [Migration("20260815010145_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("faturamento")
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Korp.Faturamento.Domain.Entities.ItemNota", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("NotaFiscalId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProdutoCodigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("produto_codigo");

                    b.Property<string>("ProdutoDescricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("produto_descricao");

                    b.Property<Guid>("ProdutoId")
                        .HasColumnType("uuid")
                        .HasColumnName("produto_id");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer")
                        .HasColumnName("quantidade");

                    b.Property<Guid>("nota_fiscal_id")
                        .HasColumnType("uuid")
                        .HasColumnName("nota_fiscal_id");

                    b.HasKey("Id");

                    b.HasIndex("nota_fiscal_id");

                    b.ToTable("itens_nota", "faturamento", t =>
                        {
                            t.HasCheckConstraint("chk_itens_nota_quantidade", "quantidade > 0");
                        });
                });

            modelBuilder.Entity("Korp.Faturamento.Domain.Entities.NotaFiscal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("ImpressoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("impresso_em");

                    b.Property<int>("Numero")
                        .HasColumnType("integer")
                        .HasColumnName("numero");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Numero")
                        .IsUnique()
                        .HasDatabaseName("idx_notas_fiscais_numero");

                    b.ToTable("notas_fiscais", "faturamento");
                });

            modelBuilder.Entity("Korp.Faturamento.Infrastructure.Idempotency.IdempotencyKey", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("key");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ResponseBody")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("response_body");

                    b.HasKey("Key");

                    b.ToTable("idempotency_keys", "faturamento");
                });

            modelBuilder.Entity("Korp.Faturamento.Domain.Entities.ItemNota", b =>
                {
                    b.HasOne("Korp.Faturamento.Domain.Entities.NotaFiscal", null)
                        .WithMany("Itens")
                        .HasForeignKey("nota_fiscal_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Korp.Faturamento.Domain.Entities.NotaFiscal", b =>
                {
                    b.Navigation("Itens");
                });
#pragma warning restore 612, 618
        }
    }
}
